language: clojure
script:
  - lein do clean, test :ci
  - lein do clean, with-profile +1.6 test :ci
jdk:
  - oraclejdk8
  - oraclejdk7
sudo: false
branches:
  only:
    - master
    - 0.7.x
    - api-experimentation
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
